service: serverless-simple-http-endpoint

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: /
          method: get
          cors:
            origins:
              - ‘*’